### ISSUE TITLE
Tests Failling

### ISSUE THREAD

**Issue by felipediesel** [annacruz/ofx#17]
I am trying to update my projects, but I realize now that a lot of tests are breaking. 

This is happening to you also? I can check that and make it work again.

**Comment by douglaslise** [comment]
@felipediesel @annacruz I have fixed all the tests on pull request #18 , just merge it and all will be fine. Thanks.

**Comment by felipediesel** [comment]
@douglaslise You pull request seems fine for me, but it is up to @annacruz to merge it.

Thank you

**Comment by douglaslise** [comment]
OK, let's wait for the merge, thanks

**Comment by kriansa** [comment]
#18 has been merged. @douglaslise can you confirm it's fixed then close this issue?

Thanks!
