### ISSUE TITLE
1.0 release?

### ISSUE THREAD

**Issue by ioquatix** [annacruz/ofx#19]
Hey, this is an awesome library and thanks for still working on it (e.g. issues and PRs).

It would be awesome if you could make a 1.0 release. The API seems stable enough and it's working well for our requirements. It's just sad when a library sits in "0.x" development for an eternity. Even if you are not fully happy, even just releasing the current 0.3.0 as 1.0 would be fine.

**Comment by thbar** [comment]
FYI I found a regression #20 on master.

**Comment by douglaslise** [comment]
Pull request #18 fixes all tests and could be merged with master

**Comment by floehopper** [comment]
Thanks for your work on this gem. Is there any chance you could release a new version of the gem, even if only with a "0.x" version...? It would be nice to avoid having to point at the git repo in my `Gemfile`.

**Comment by ioquatix** [comment]
Bump :)
