### ISSUE TITLE
Regression in master (compared to 0.3.2)

### ISSUE THREAD

**Issue by thbar** [annacruz/ofx#20]
Today I upgraded my code from the latest gem version (`0.3.2`) to master (at 3c084de7ff943a8d1c2c0f4852aba30c88f304e5), and the parser started choking on the files:

```
ArgumentError: wrong number of arguments (given 1, expected 0)
  /Users/thbar/.rvm/gems/ruby-2.4.0/bundler/gems/ofx-3c084de7ff94/lib/ofx/parser/ofx102.rb:116:in `build_balance'
  /Users/thbar/.rvm/gems/ruby-2.4.0/bundler/gems/ofx-3c084de7ff94/lib/ofx/parser/ofx102.rb:63:in `build_account'
  /Users/thbar/.rvm/gems/ruby-2.4.0/bundler/gems/ofx-3c084de7ff94/lib/ofx/parser/ofx102.rb:31:in `account'
```

I cannot at this point provide data (yet), but I still wanted to open the issue to avoid seeing a 1.0 release with that regression included.

**Comment by douglaslise** [comment]
Pull request #18 fixes all tests and could be merged with master

**Comment by thbar** [comment]
@douglaslise I'll try your branch on my file and will report back to confirm if everything runs smoothly, thanks!

**Comment by thbar** [comment]
@douglaslise I just tested my code against `gem 'ofx', git: 'https://github.com/douglaslise/ofx', ref: 'fix-tests'` and indeed this fixes the issue I've reported here (cc @annacruz).

**Comment by kriansa** [comment]
#18 has been merged. @thbar can you confirm it's fixed?

**Comment by thbar** [comment]
@kriansa I will test (must find the original file, it's been a while) and will report. Please keep the issue opened, I'm adding a reminder to self!

**Comment by ioquatix** [comment]
Bump :)

**Comment by thbar** [comment]
Hey! I have done some testing today:
- I was able to reproduce the error with 3c084de
- Upgrading to current `master` branch (03a1f98) solves the issue

I think it is good!

The only sidenote is that #44 should be also merged in, because I got that `BigDecimal` warning, it would be good to fix it before a release.

I suggest we leave the issue opened, until a release is made, at which point I'll verify and close.

What do you think?

**Comment by ioquatix** [comment]
@annacruz bump :) do you need help to maintain this gem?

**Comment by thbar** [comment]
Closing this one.
