### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by cesarjr** [annacruz/ofx#61]
Hi!

We'd like to use this gem in your project but we noticed that the last commit was in 2019.

Does anyone know if this project is still being maintained?

Thanks.

**Comment by dmitryrck** [comment]
I think it is abandonaware.

I have a fork ([https://github.com/dmitryrck/ofx](https://github.com/dmitryrck/ofx)) that I am using on this project [https://github.com/dmitryrck/organize2](https://github.com/dmitryrck/organize2) (This PR, actually: https://github.com/dmitryrck/organize2/pull/40 ).

I intend to keep updating both of the projects; organize2 for example is a 5 years old project that I use every day.

**Comment by annacruz** [comment]
@dmitryrck Could you please make a new PR so we can update this project?
I'm planning to restart the maintanance of it. 
Sorry for that....

**Comment by dmitryrck** [comment]
> @dmitryrck Could you please make a new PR so we can update this project?
> I'm planning to restart the maintanance of it.
> Sorry for that....

Sure, will do, give me some time :D

**Comment by annacruz** [comment]
Thanks a lot =)

**Comment by dmitryrck** [comment]
The fixes I did are already merged on your/this remote. The other things I did are minor (replace Travis with Github Actions, for example).

I don't believe there is any need of a PR from my side :wink:.

**Comment by annacruz** [comment]
Great @dmitryrck I'll just do some other small improvements and create a new gem version. Can I close this issue? /cc @cesarjr

**Comment by cesarjr** [comment]
Yeah @annacruz !

We're very happy over here that you're back.

<img width=30% src=https://media.giphy.com/media/l2JdXy8xasypvE0Ni/giphy.gif>

Actually, we're already using, in production, the most recent master commit.

![image](https://user-images.githubusercontent.com/824198/121393229-88715100-c926-11eb-8dff-2927df3de600.png)

I'd like to thank you again for your great job.

If you require any kind of support, please let us know.

**Comment by annacruz** [comment]
@ashkulz again sorry for the huge delay, will do that today...

**Comment by ashkulz** [comment]
@annacruz I guess you didn't get the time, is it possible to do so in the near future?

**Comment by annacruz** [comment]
@ashkulz you were right, I did some stuff but forgot to update in rubygems, just did that.
In the near future I'll reserve at least 1-2 hours a week to maintain the gem because of the latest (or not that latests) ruby improvements.

**Comment by ashkulz** [comment]
Thanks, @annacruz! Unfortunately, I think 986c037d91c97bc50e244696f324182098042613 doesn't work on Ruby 2.x due to the syntax changes :man_shrugging:

**Comment by annacruz** [comment]
@ashkulz adjusted =)
