### ISSUE TITLE
Multiple statements/accounts per file

### ISSUE THREAD

**Issue by nathanaeljones** [annacruz/ofx#9]
Fantastic library! Found a curveball you might be interested in, however.

American Express lets customers export a single .ofx file containing multiple statements from multiple credit cards. 

Each statement has a repetition of the account number, balance, etc. 

While it's easy to have a separate .ofx per CC account, it may be an invalid assumption that there is a 1-1 relationship between .ofx and account.

In my use case, I need to access the balance for each month, but only the first balance is available through the current API. 

I can send you a sample file if you like.

**Comment by annacruz** [comment]
Since I merged the PR I'll close this issue.
