### ISSUE TITLE
Pull requests

### ISSUE THREAD

**Issue by marcosdemelo** [annacruz/ofx#94]
Hi @annacruz, did you see that in my last pull requests that you integrated, all the commits I made in the working branches appeared in the `main` branch?

It didn't have any really bad messages, but I'd like to know what you think of doing a `squash` when you integrate PR into the `main` branch?

It would even be possible to configure Github to show this option by default:

To configure: https://github.com/annacruz/ofx/settings

<img width="798" alt="image" src="https://user-images.githubusercontent.com/1786713/188453622-5ce297f2-abe3-4e82-aa96-00734a579027.png">

**Comment by annacruz** [comment]
You are right @marcosdemelo I was just doing the default things... I'll reconfigure it. Thanks for the advice.
