### ISSUE TITLE
0.3.5 is broken on rubygems

### ISSUE THREAD

**Issue by JoeDupuis** [annacruz/ofx#99]
I am hitting this issue too : https://github.com/annacruz/ofx/issues/96
It looks like the 0.3.5 hosted on rubygems differs from the repo.
I diffed the gem against this repo and ignoring the difference caused by rubocop/standard, this [line ](https://gist.github.com/JoeDupuis/41397ce6f44ca725c6af4a1a2c596068#file-0-3-5-diff-patch-L146) is causing the issue 
The content attr_reader is missing a t.

```ruby
attr_reader :headers, :body, :conten, :parser
```
should be 
```ruby 
attr_reader :headers, :body, :content, :parser
```

I think we need to create a new re-lease to fix.

**Comment by cesarjr** [comment]
Hi Joe!

Have you tried the solution described at #96? Did it work for you? If yes, please, close this issue e continue the conversation there.

It helps to keep the repository organized.

Thank you.

**Comment by JoeDupuis** [comment]
@cesarjr it does, but it's only a workaround, not a fix. 
It works because it download the gem from the repo instead of rubygems. The rubygems version still has the bug. We should fix it as this is what newcomers will likely try first. 

We can continue on the other issue, but I can't reopen the other issue. Having the issue closed make it hard to see what is still an active issue.
